# Generated by Django 6.1.2 on 2026-10-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_cargar_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
