# Generated by Django 6.1.2 on 2026-10-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_categoria_slug_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, help_text='Sube una foto desde tu computador', upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, help_text='Se usa solo si no hay foto subida. URL o ruta /static/...', max_length=300, verbose_name='URL de imagen'),
        ),
    ]
